# General Jekyll Config
#highlighter: pygments
title: tibaal.github.io
url: https://tibaal.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

markdown: redcarpet
