title: "tibaal.github.io"
baseurl: ""
url: "https://tibaal.github.io"
footer_right: "© Michael McCambridge, 2016"

author: "Mike McCambridge"
github_username: "tibaal89"
twitter_username: "tibaal89"
linkedin_username: "michaelmccambridge"

markdown: kramdown
