title: "n0j.github.io"
baseurl: ""
url: "https://n0j.github.io"
footer_right: "© Michael McCambridge, 2017"

author: "Mike McCambridge"
github_username: "n0j"
twitter_username: "realn0j"
linkedin_username: "michaelmccambridge"

google_analytics: UA-68102464-1
disqus:
    shortname: "https-n0j-github-io"

markdown: kramdown
