# Site settings
title: tibaal.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tibaal.github.io/" # the base hostname & protocol for your site
github_username:  tibaal

# Build settings
markdown: redcarpet
